<div class="lang fixed top-0 right-0 m-5">
    <div class="dd text-gray-500 capitalize">
        <p class="p-2 border rounded-lg shadow cursor-pointer">select language <i class="text-lg fa fa-language"></i></p>
        <div class="dd-content border divide-y rounded-lg m-1 hidden">
            <a href="auth?locale=en">
                <p class="p-2 hover:bg-gray-100 cursor-pointer" data="en">English</p>
            </a>
            <a href="auth?locale=hi">
                <p class="p-2 hover:bg-gray-100 cursor-pointer" data="hi">Hindi</p>
            </a>
            <a href="auth?locale=jp">
                <p class="p-2 hover:bg-gray-100 cursor-pointer" data="jp">Japaease</p>
            </a>
        </div>
    </div>
</div>
<div class="h-screen w-screen flex text-gray-700 justify-center items-center">
    <?php
    if (isset($token)) {
    ?>
        <div class="flex flex-col justify-start w-1/2 items-center">
            <p>your Token : </p>
            <div class="overflow-auto w-1/2 text-justify token bg-gray-200 text-indigo-500 p-3 text-center border rounded-lg mt-3">
                <p><?php echo $token; ?></p>
            </div>
        </div>
    <?php
    } else {
    ?>
        <form action="#" method="post" class="flex flex-col">
            <label for="logo" class="text-center">
                <i class="fa fa-box text-7xl text-indigo-500"></i>
            </label>
            <label for="email">
                <p class="p-2"><i class="fa fa-envelope text-sm text-indigo-500"></i> <?php echo $t->_('email'); ?></p>
                <input type="text" class="rounded-lg border-gray-300" name="email" id="" placeholder="<?php echo $t->_('putemail'); ?>" required>
            </label>
            <label for="email">
                <p class="p-2"><i class="fa fa-lock text-sm text-indigo-500"></i> <?php echo $t->_('password'); ?></p>
                <input type="password" class="rounded-lg border-gray-300" name="password" id="" placeholder="<?php echo $t->_('putpassword'); ?>" required>
            </label>
            <label for="email">
                <p class="p-2"><i class="fa fa-users text-sm text-indigo-500"></i> <?php echo $t->_('role'); ?></p>
                <select name="selectrole" id="" class="rounded-lg border-gray-300 w-full" required>
                    <option value=""><?php echo $t->_('selectrole'); ?></option>
                    <?php
                    foreach ($data as $role) {
                    ?>
                        <option value="<?php echo $role->role_name; ?>"><?php echo $role->role_name; ?></option>
                    <?php
                    }
                    ?>
                </select>
            </label>
            <label for="rem" class="flex items-center mt-3 mx-1">
                <input type="checkbox" class="mr-2 appearance-none checked:bg-indigo-500 border-indigo-500 border-2" name="" id="">
                <p><?php echo $t->_('rememberme'); ?></p>
            </label>
            <button type="submit" class="border-2 text-indigo-500 p-2 mt-4 hover:bg-indigo-500 hover:text-white shadow-lg rounded-lg border-indigo-500"><?php echo $t->_('register'); ?></button>
        </form>
    <?php
    }
    ?>
</div>