<div class="lang fixed top-0 right-0 m-5 bg-white rounded-lg">
    <div class="dd text-gray-500 capitalize">
        <p class="p-2 border rounded-lg shadow cursor-pointer">select language <i class="text-lg fa fa-language"></i></p>
        <div class="dd-content border divide-y rounded-lg m-1 hidden">
            <a href="order?locale=en&bearer=<?php echo $token; ?>">
                <p class="p-2 hover:bg-gray-100 cursor-pointer" data="en">English</p>
            </a>
            <a href="order?locale=hi&bearer=<?php echo $token; ?>">
                <p class="p-2 hover:bg-gray-100 cursor-pointer" data="hi">Hindi</p>
            </a>
            <a href="order?locale=jp&bearer=<?php echo $token; ?>">
                <p class="p-2 hover:bg-gray-100 cursor-pointer" data="jp">Japaease</p>
            </a>
        </div>
    </div>
</div>
<div class="h-screen capitalize w-screen bg-gray-200 flex justify-center items-center">
    <div class="flex text-slate-700 bg-white rounded-lg shadow-sm w-3/4<div class=" h-screen w-screen bg-gray-200 flex justify-center items-center">
        <table class="p-3">
            <thead>
                <tr class="shadow">
                    <th class="p-3 border"><?php echo $t->_('Customer Name'); ?></th>
                    <th class="p-3 border"><?php echo $t->_('Customer Address'); ?></th>
                    <th class="p-3 border"><?php echo $t->_('Zipcode'); ?></th>
                    <th class="p-3 border"><?php echo $t->_('Product Id'); ?></th>
                    <th class="p-3 border"><?php echo $t->_('Product Quantity'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($data as $order) {
                ?>
                    <tr class="odd:bg-gray-100 leading-relaxed even:bg-white cursor-pointer hover:bg-gray-100">
                        <td class="p-3 border"><?php echo $order->customer_name ?></td>
                        <td class="p-3 border"><?php echo $order->customer_address ?></td>
                        <td class="p-3 border"><?php echo $order->zipcode ?></td>
                        <td class="p-3 border"><?php echo $order->product_id ?></td>
                        <td class="p-3 border"><?php echo $order->quantity ?></td>
                    </tr>
                <?php
                }
                ?>
            </tbody>
        </table>

    </div>

</div>
</div>